export const products = [
  {
    id: "1",
    description: "The Heights",
    slug: "the-heights",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/heights.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "2",
    description: "My Love",
    slug: "my-love",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/mylove.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "3",
    description: "Slide",
    slug: "slide",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/slide.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "4",
    description: "Dancing Girl",
    slug: "dancing-girl",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/dance.jpeg",
    videoURL: "",
    createtdAt: "",
  },
];