export const products = [
  {
    id: "1",
    name: "The Heights",
    slug: "the-heights",
    description: "A stunning aerial view capturing the majestic beauty of towering landscapes. This piece brings a sense of elevation and perspective to any space, perfect for those who appreciate dramatic natural vistas.",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/heights.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "2",
    name: "My Love",
    slug: "my-love",
    description: "An intimate and heartfelt artistic expression that celebrates romance and connection. This emotionally evocative piece adds warmth and tenderness to your living space, ideal for bedrooms or personal areas.",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/mylove.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "3",
    name: "Slide",
    slug: "slide",
    description: "A dynamic composition capturing the joy and movement of playful moments. This energetic artwork brings a sense of fun and nostalgia, making it perfect for family spaces or creative environments.",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/slide.jpeg",
    videoURL: "",
    createtdAt: "",
  },
  {
    id: "4",
    name: "Dancing Girl",
    slug: "dancing-girl",
    description: "A graceful depiction of movement and expression through dance. This elegant piece captures the fluidity and passion of motion, bringing life and artistic sophistication to any room.",
    price: "$25",
    size: {
      1: "8 X 12",
      2: "12 X 16",
    },
    discount: "",
    imageURL: "/dance.jpeg",
    videoURL: "",
    createtdAt: "",
  },
];